/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliticaEnvioRouteImport } from './routes/politica-envio'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as PoliticaReembolsoRouteImport } from './routes/politica-reembolso'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ObrigadoIdRouteImport } from './routes/obrigado.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as UpsellIdRouteImport } from './routes/upsell.$id'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEnvioRoute = PoliticaEnvioRouteImport.update({
  id: '/politica-envio',
  path: '/politica-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaReembolsoRoute = PoliticaReembolsoRouteImport.update({
  id: '/politica-reembolso',
  path: '/politica-reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoIdRoute = ObrigadoIdRouteImport.update({
  id: '/obrigado/$id',
  path: '/obrigado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellIdRoute = UpsellIdRouteImport.update({
  id: '/upsell/$id',
  path: '/upsell/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix-webhook',
  path: '/api/public/pix-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/obrigado/$id': typeof ObrigadoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/upsell/$id': typeof UpsellIdRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/obrigado/$id': typeof ObrigadoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/upsell/$id': typeof UpsellIdRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-envio': typeof PoliticaEnvioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/politica-reembolso': typeof PoliticaReembolsoRoute
  '/produto': typeof ProdutoRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/obrigado/$id': typeof ObrigadoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/upsell/$id': typeof UpsellIdRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/obrigado/$id'
    | '/pedido/$id'
    | '/upsell/$id'
    | '/api/public/pix-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/obrigado/$id'
    | '/pedido/$id'
    | '/upsell/$id'
    | '/api/public/pix-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/politica-envio'
    | '/politica-privacidade'
    | '/politica-reembolso'
    | '/produto'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/obrigado/$id'
    | '/pedido/$id'
    | '/upsell/$id'
    | '/api/public/pix-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  PoliticaEnvioRoute: typeof PoliticaEnvioRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PoliticaReembolsoRoute: typeof PoliticaReembolsoRoute
  ProdutoRoute: typeof ProdutoRoute
  RastreioRoute: typeof RastreioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ObrigadoIdRoute: typeof ObrigadoIdRoute
  PedidoIdRoute: typeof PedidoIdRoute
  UpsellIdRoute: typeof UpsellIdRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-envio': {
      id: '/politica-envio'
      path: '/politica-envio'
      fullPath: '/politica-envio'
      preLoaderRoute: typeof PoliticaEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-reembolso': {
      id: '/politica-reembolso'
      path: '/politica-reembolso'
      fullPath: '/politica-reembolso'
      preLoaderRoute: typeof PoliticaReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado/$id': {
      id: '/obrigado/$id'
      path: '/obrigado/$id'
      fullPath: '/obrigado/$id'
      preLoaderRoute: typeof ObrigadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/$id': {
      id: '/upsell/$id'
      path: '/upsell/$id'
      fullPath: '/upsell/$id'
      preLoaderRoute: typeof UpsellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-webhook': {
      id: '/api/public/pix-webhook'
      path: '/api/public/pix-webhook'
      fullPath: '/api/public/pix-webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  PoliticaEnvioRoute: PoliticaEnvioRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PoliticaReembolsoRoute: PoliticaReembolsoRoute,
  ProdutoRoute: ProdutoRoute,
  RastreioRoute: RastreioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ObrigadoIdRoute: ObrigadoIdRoute,
  PedidoIdRoute: PedidoIdRoute,
  UpsellIdRoute: UpsellIdRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
